apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration
archiveSize: 15 #<- this will be the size of each tar. Change if needed
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.20
      packages:
       - name: rhods-operator
         defaultChannel: fast-3.x
         channels:
         - name: fast-3.x
           minVersion: '3.0.0'
           maxVersion: '3.0.0’
